# Generated by Django 3.0 on 2019-12-07 05:50

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='about',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='balance',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='company_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='people',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='eyeColor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='favouriteFood',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='people',
            name='friends',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='people',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='greeting',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='guid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='has_died',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='people',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='picture',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='registered',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AddField(
            model_name='people',
            name='tags',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='people',
            name='index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
